import { create } from 'zustand'

export type Language = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr'

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome to AI SATHI",
    welcome_ai: "Namaste! I am your AI SATHI. How can I help you today?",
    select_language: "Select Your Language",
    farming: "Farming",
    emergency: "Emergency",
    govt_help: "Govt. Help",
    ai_chat: "AI Chat",
    weather: "Weather",
    crop_disease: "Crop Disease",
    settings: "Settings",
    medicine_reader: "Medicine Reader",
    medicine_reader_desc: "Scan medicine to hear instructions",
    smart_tips: "Smart Tips",
    ask_anything: "Ask me anything...",
    start: "Start",
    back: "Back",
    home: "Home",
    offline_mode: "Offline Mode",
    online_mode: "Online Mode",
    listening: "Listening...",
    tap_mic: "Tap microphone to speak",
    profile: "Profile",
    language_label: "Language",
    notifications: "Notifications",
    dark_mode: "Dark Mode",
    privacy: "Privacy & Security",
    help_about: "Help & About",
    privacy_detail: "Your data stays on your phone. We do not share your location or identity. Offline mode ensures 100% privacy.",
    about_detail: "AI SATHI (KrishiMitro) is designed for rural empowerment. It works without internet to provide critical farming and emergency advice.",
    sign_out: "Sign Out",
    confirm_sign_out: "Are you sure you want to sign out?",
    scheme_kisan_title: "PM-Kisan Nidhi",
    scheme_kisan_desc: "₹6,000 yearly for farmers",
    scheme_bima_title: "Fasal Bima Yojana",
    scheme_bima_desc: "Crop insurance against loss",
    scheme_kcc_title: "Kisan Credit Card",
    scheme_kcc_desc: "Low interest loans for farming",
    contact_police: "Call Police",
    contact_police_desc: "Dial 100",
    contact_medical: "Medical Help",
    contact_medical_desc: "Dial 108",
    contact_family: "Family Contact",
    contact_family_desc: "Notify family",
    farming_tip_organic_title: "Use Organic Fertilizer",
    farming_tip_organic_desc: "Improves soil health by 40%",
    farming_tip_rotation_title: "Crop Rotation",
    farming_tip_rotation_desc: "Prevents soil nutrient depletion",
    sos_active: "S O S Activated. Emergency contacts notified.",
    login_welcome_back: "Welcome Back",
    login_create_account: "Create Account",
    login_full_name: "Full Name",
    login_phone_number: "Phone Number",
    login_password: "OTP / Password",
    login_create_password: "Create Password",
    login_button: "Login",
    register_button: "Register",
    login_new_here: "New here? Create an account",
    login_already_have_account: "Already have an account? Login",
    login_error_password_length: "Password must be at least 4 characters",
    login_error_phone_not_registered: "Phone number not registered",
    login_error_wrong_password: "Wrong password",
    login_digital_farming_companion: "Your digital farming companion",
    login_secure_auth: "Secure offline-first authentication",
    personalize_experience: "Personalize Experience",
    select_primary_language: "Please select your primary language",
    weather_alerts: "Weather Emergency Alerts",
    flood_risk: "Flood Risk",
    storm_severity: "Storm Severity",
    wind_speed: "Wind Speed",
    rain_prob: "Rain Probability",
    temp: "Temperature",
    humidity: "Humidity",
    safe: "Safe",
    moderate_risk: "Moderate Risk",
    dangerous: "Dangerous",
    ai_suggestions: "AI Safety Suggestions",
    protect_crops: "Protect your standing crops",
    store_grains: "Store harvested grains indoors",
    disconnect_irrigation: "Disconnect irrigation motors",
    shelter_livestock: "Move livestock to elevated shelter",
    offline_alerts: "Offline Mode: Last updated alerts available",
    heavy_rain_warning: "Heavy rainfall expected in next 3 hours",
    high_wind_warning: "High wind speed alert for farming areas",
    flood_warning: "Flood warning issued for low-lying regions",
    animal_emergency: "Livestock Emergency Help",
    select_animal: "Select Animal",
    cow: "Cow",
    goat: "Goat",
    buffalo: "Buffalo",
    chicken: "Chicken",
    describe_symptoms: "Describe Symptoms",
    symptoms_placeholder: "e.g. not eating, fever, injury...",
    upload_photo: "Upload Animal Photo",
    analyzing: "AI Analyzing Health...",
    ai_vet_report: "AI Veterinary Report",
    seriousness: "Emergency Level",
    possible_condition: "Possible Condition",
    first_aid: "First Aid Advice",
    hydration: "Hydration Advice",
    mild: "Mild",
    moderate_level: "Moderate",
    critical: "Critical",
    nearby_vet: "Nearby Veterinary Help",
    vet_distance: "km away",
    call_vet: "Call Doctor",
    machine_emergency: "Machine Emergency Help",
    select_machine: "Select Machine",
    tractor: "Tractor",
    pump: "Water Pump",
    motor: "Irrigation Motor",
    harvester: "Harvester",
    describe_problem: "Describe Problem",
    problem_placeholder: "e.g. not starting, overheating, unusual sound...",
    troubleshooting: "AI Troubleshooting Steps",
    severity_level: "Severity Level",
    mechanic_help: "Nearby Mechanic Help",
    call_mechanic: "Call Mechanic",
    not_starting: "Not Starting",
    overheating: "Overheating",
    leakage: "Leakage",
    unusual_sound: "Unusual Sound",
    low_power: "Low Power",
    machine_fault_critical: "Critical Fuel/Oil Leakage or Engine Failure",
    machine_fault_medium: "Battery/Electrical Fault or Clogged Filter",
    machine_fault_low: "General Maintenance Required",
    step_turn_off: "Turn off engine immediately",
    step_disconnect_battery: "Disconnect battery terminals",
    step_check_leaks: "Check for flammable fluid leaks",
    step_no_restart: "Do not attempt to restart",
    step_check_fluids: "Check fuel/oil levels",
    step_clean_filter: "Clean the air filter intake",
    step_check_voltage: "Check battery voltage connections",
    step_listen_noise: "Listen for specific noise patterns",
    high_risk: "High",
    medium_risk: "Medium",
    low_risk: "Low",
    market_dashboard: "Live Market Prices",
    crop_rice: "Rice",
    crop_potato: "Potato",
    crop_wheat: "Wheat",
    crop_onion: "Onion",
    crop_tomato: "Tomato",
    crop_mustard: "Mustard",
    market_demand: "Market Demand",
    high_demand: "High Demand",
    stable: "Stable",
    falling: "Falling",
    urgent_sell: "Urgent Sell",
    sell_recommendation: "AI Selling Tip",
    profit_estimator: "Profit Estimator",
    enter_quantity: "Enter Quantity (kg)",
    estimated_earnings: "Estimated Earnings",
    best_time_to_sell: "Best Selling Time",
    search_crop: "Search for crop...",
    sort_by: "Sort By",
    highest_price: "Highest Price",
    biggest_increase: "Biggest Increase",
    today_price: "Today's Price",
    last_updated: "Last Updated",
    offline_market: "Offline: Last synced prices",
    select_crop: "Select Crop",
    best_time_is: "Best selling month: ",
    jan: "January", feb: "February", mar: "March", apr: "April", may: "May", jun: "June",
    jul: "July", aug: "August", sep: "September", oct: "October", nov: "November", dec: "December",
    crop_doctor: "Crop Doctor",
    soil_analyzer: "Soil Analyzer",
    smart_irrigation: "Smart Irrigation",
    pest_alert: "Pest Alert",
    farming_calendar: "Farming Calendar",
    smart_tools: "Smart Farming Tools",
    market_intelligence: "Market Intelligence Dashboard",
    tool_doctor_res: "Crop Health: Healthy. Minimal nitrogen deficiency detected. Suggest adding compost.",
    tool_soil_res: "Soil Status: Loamy. pH 6.5 (Optimal). Organic carbon is good.",
    tool_irrigation_res: "Irrigation Tip: Low evaporation today. Scheduled watering at 6:00 PM.",
    tool_pest_res: "Pest Risk: Low. Humidity is high, watch for fungal growth in tomatoes.",
    tool_calendar_res: "Calendar: Ideal for sowing Mustard and Onion this week.",
    ai_analysis_complete: "AI Analysis Complete",
    close: "Close",
    maximize_income: "Maximize Your Farming Income",
    estimate_earnings_desc: "Estimate your earnings based on current live market data and predicted trends.",
    active_farmers: "Active Farmers",
    market_focus: "Market Focus",
    farming_intel_v1: "Farming Intelligence v1.0",
    wait_rising: "Prices rising. Wait 2 days.",
    urgent_sell_desc: "Price dropping rapidly.",
    market_stable_desc: "Market is stable.",
    data_provided_by: "Data Provided by Meteorological & Market Intelligence Dept.",
    wb_region: "WB REGION",
  },
  hi: {
    welcome: "AI SATHI में आपका स्वागत है",
    welcome_ai: "नमस्ते! मैं आपका एआई साथी हूँ। आज मैं आपकी क्या मदद कर सकता हूँ?",
    select_language: "अपनी भाषा चुनें",
    farming: "खेती",
    emergency: "आपातकालीन",
    govt_help: "सरकारी सहायता",
    ai_chat: "AI चैट",
    weather: "मौसम",
    crop_disease: "फसल रोग",
    settings: "सेटिंग्स",
    medicine_reader: "दवा पाठक",
    medicine_reader_desc: "निर्देश सुनने के लिए दवा को स्कैन करें",
    smart_tips: "स्मार्ट टिप्स",
    ask_anything: "मुझसे कुछ भी पूछें...",
    start: "शुरू करें",
    back: "पीछे",
    home: "होम",
    offline_mode: "ऑफलाइन मोड",
    online_mode: "ऑनलाइन मोड",
    listening: "सुन रहा हूँ...",
    tap_mic: "बोलने के लिए माइक दबाएं",
    profile: "प्रोफ़ाइल",
    language_label: "भाषा",
    notifications: "सूचनाएं",
    dark_mode: "डार्क मोड",
    privacy: "गोपनीयता और सुरक्षा",
    help_about: "सहायता और जानकारी",
    privacy_detail: "आपका डेटा आपके फोन पर रहता है। हम आपकी लोकेशन या पहचान साझा नहीं करते हैं। ऑफलाइन मोड 100% गोपनीयता सुनिश्चित करता है।",
    about_detail: "AI SATHI (कृषिमित्रो) ग्रामीण सशक्तिकरण के लिए बनाया गया है। यह महत्वपूर्ण खेती और आपातकालीन सलाह देने के लिए इंटरनेट के बिना काम करता है।",
    sign_out: "साइन आउट",
    confirm_sign_out: "क्या आप वाकई साइन आउट करना चाहते हैं?",
    scheme_kisan_title: "PM-किसान निधि",
    scheme_kisan_desc: "किसानों के लिए ₹6,000 वार्षिक",
    scheme_bima_title: "फसल बीमा योजना",
    scheme_bima_desc: "नुकसान के खिलाफ फसल बीमा",
    scheme_kcc_title: "किसान क्रेडिट कार्ड",
    scheme_kcc_desc: "खेती के लिए कम ब्याज ऋण",
    contact_police: "पुलिस को बुलाओ",
    contact_police_desc: "100 डायल करें",
    contact_medical: "चिकित्सा सहायता",
    contact_medical_desc: "108 डायल करें",
    contact_family: "परिवार का संपर्क",
    contact_family_desc: "परिवार को सूचित करें",
    farming_tip_organic_title: "जैविक उर्वरक का प्रयोग करें",
    farming_tip_organic_desc: "मिट्टी के स्वास्थ्य में 40% सुधार",
    farming_tip_rotation_title: "फसल चक्र",
    farming_tip_rotation_desc: "मिट्टी के पोषक तत्वों की कमी को रोकता है",
    sos_active: "एस ओ एस सक्रिय। आपातकालीन संपर्कों को सूचित किया गया।",
    login_welcome_back: "वापसी पर स्वागत है",
    login_create_account: "खाता बनाएं",
    login_full_name: "पूरा नाम",
    login_phone_number: "फ़ोन नंबर",
    login_password: "ओटीपी / पासवर्ड",
    login_create_password: "पासवर्ड बनाएं",
    login_button: "लॉगिन",
    register_button: "पंजीकरण",
    login_new_here: "नए हैं? खाता बनाएं",
    login_already_have_account: "पहले से ही खाता है? लॉगिन करें",
    login_error_password_length: "पासवर्ड कम से कम 4 अक्षरों का होना चाहिए",
    login_error_phone_not_registered: "फ़ोन नंबर पंजीकृत नहीं है",
    login_error_wrong_password: "गलत पासवर्ड",
    login_digital_farming_companion: "आपका डिजिटल खेती साथी",
    login_secure_auth: "सुरक्षित ऑफलाइन-प्रथम प्रमाणीकरण",
    personalize_experience: "अनुभव को निजीकृत करें",
    select_primary_language: "कृपया अपनी प्राथमिक भाषा चुनें",
    weather_alerts: "मौसम आपातकालीन अलर्ट",
    flood_risk: "बाढ़ का खतरा",
    storm_severity: "तूफान की तीव्रता",
    wind_speed: "हवा की गति",
    rain_prob: "बारिश की संभावना",
    temp: "तापमान",
    humidity: "नमी",
    safe: "सुरक्षित",
    moderate_risk: "मध्यम जोखिम",
    dangerous: "खतरनाक",
    ai_suggestions: "एआई सुरक्षा सुझाव",
    protect_crops: "अपनी खड़ी फसलों की रक्षा करें",
    store_grains: "कटी हुई फसलों को घर के अंदर रखें",
    disconnect_irrigation: "सिंचाई मोटरों को बंद करें",
    shelter_livestock: "पशुओं को ऊंचे स्थान पर ले जाएं",
    offline_alerts: "ऑफलाइन मोड: अंतिम अपडेट अलर्ट उपलब्ध",
    heavy_rain_warning: "अगले 3 घंटों में भारी बारिश की संभावना",
    high_wind_warning: "खेती क्षेत्रों के लिए तेज हवा की चेतावनी",
    flood_warning: "निचले क्षेत्रों के लिए बाढ़ की चेतावनी जारी",
    animal_emergency: "पशु आपातकालीन सहायता",
    select_animal: "पशु चुनें",
    cow: "गाय",
    goat: "बकरी",
    buffalo: "भैंस",
    chicken: "मुर्गी",
    describe_symptoms: "लक्षणों का वर्णन करें",
    symptoms_placeholder: "जैसे - खाना न खाना, बुखार, चोट...",
    upload_photo: "पशु की फोटो अपलोड करें",
    analyzing: "एआई स्वास्थ्य विश्लेषण कर रहा है...",
    ai_vet_report: "एआई पशु चिकित्सा रिपोर्ट",
    seriousness: "आपातकालीन स्तर",
    possible_condition: "संभावित स्थिति",
    first_aid: "प्राथमिक उपचार सलाह",
    hydration: "जलयोजन सलाह",
    mild: "हल्का",
    moderate_level: "मध्यम",
    critical: "गंभीर",
    nearby_vet: "नजदीकी पशु चिकित्सा सहायता",
    vet_distance: "किमी दूर",
    call_vet: "डॉक्टर को बुलाएं",
    machine_emergency: "मशीन आपातकालीन सहायता",
    select_machine: "मशीन चुनें",
    tractor: "ट्रैक्टर",
    pump: "पानी का पंप",
    motor: "सिंचाई मोटर",
    harvester: "हार्वेस्टर",
    describe_problem: "समस्या का वर्णन करें",
    problem_placeholder: "जैसे - स्टार्ट न होना, गरम होना, अजीब आवाज...",
    troubleshooting: "एआई समस्या निवारण कदम",
    severity_level: "गंभीरता स्तर",
    mechanic_help: "नजदीकी मैकेनिक सहायता",
    call_mechanic: "मैकेनिक को बुलाएं",
    not_starting: "स्टार्ट नहीं हो रहा",
    overheating: "ज़्यादा गरम होना",
    leakage: "रिसाव (लीकेज)",
    unusual_sound: "अजीब आवाज",
    low_power: "कम शक्ति",
    machine_fault_critical: "गंभीर ईंधन/तेल रिसाव या इंजन की विफलता",
    machine_fault_medium: "बैटरी/विद्युत दोष या बंद फ़िल्टर",
    machine_fault_low: "सामान्य रखरखाव की आवश्यकता",
    step_turn_off: "इंजन तुरंत बंद करें",
    step_disconnect_battery: "बैटरी टर्मिनलों को डिस्कनेक्ट करें",
    step_check_leaks: "ज्वलनशील तरल रिसाव की जाँच करें",
    step_no_restart: "दोबारा स्टार्ट करने का प्रयास न करें",
    step_check_fluids: "ईंधन/तेल के स्तर की जाँच करें",
    step_clean_filter: "एयर फिल्टर इनटेक को साफ करें",
    step_check_voltage: "बैटरी वोल्टेज कनेक्शन की जाँच करें",
    step_listen_noise: "विशिष्ट शोर पैटर्न को सुनें",
    high_risk: "उच्च",
    medium_risk: "मध्यम",
    low_risk: "कम",
    market_dashboard: "लाइव बाजार भाव",
    crop_rice: "चावल",
    crop_potato: "आलू",
    crop_wheat: "गेहूं",
    crop_onion: "प्याज",
    crop_tomato: "टमाटर",
    crop_mustard: "सरसों",
    market_demand: "बाजार की मांग",
    high_demand: "अधिक मांग",
    stable: "स्थिर",
    falling: "गिर रहा है",
    urgent_sell: "तुरंत बेचें",
    sell_recommendation: "एआई बिक्री सुझाव",
    profit_estimator: "लाभ अनुमानक",
    enter_quantity: "मात्रा दर्ज करें (किग्रा)",
    estimated_earnings: "अनुमानित कमाई",
    best_time_to_sell: "बेचने का सबसे अच्छा समय",
    search_crop: "फसल खोजें...",
    sort_by: "क्रमबद्ध करें",
    highest_price: "उच्चतम कीमत",
    biggest_increase: "सबसे बड़ी वृद्धि",
    today_price: "आज का भाव",
    last_updated: "अंतिम अपडेट",
    offline_market: "ऑफलाइन: अंतिम सिंक किए गए भाव",
    select_crop: "फसल चुनें",
    best_time_is: "बेचने का सबसे अच्छा महीना: ",
    jan: "जनवरी", feb: "फरवरी", mar: "मार्च", apr: "अप्रैल", may: "मई", jun: "जून",
    jul: "जुलाई", aug: "अगस्त", sep: "सितंबर", oct: "अक्टूबर", nov: "नवंबर", dec: "दिसंबर",
    crop_doctor: "फसल डॉक्टर",
    soil_analyzer: "मिट्टी विश्लेषक",
    smart_irrigation: "स्मार्ट सिंचाई",
    pest_alert: "कीट चेतावनी",
    farming_calendar: "खेती कैलेंडर",
    smart_tools: "स्मार्ट खेती उपकरण",
    market_intelligence: "बाजार खुफिया डैशबोर्ड",
    tool_doctor_res: "फसल स्वास्थ्य: स्वस्थ। नाइट्रोजन की हल्की कमी। जैविक खाद डालने का सुझाव।",
    tool_soil_res: "मिट्टी की स्थिति: दोमट। पीएच 6.5 (सर्वोत्तम)। जैविक कार्बन अच्छा है।",
    tool_irrigation_res: "सिंचाई टिप: आज वाष्पीकरण कम है। शाम 6:00 बजे पानी देने का समय।",
    tool_pest_res: "कीट जोखिम: कम। नमी अधिक है, टमाटर में फफूंद की जांच करें।",
    tool_calendar_res: "कैलेंडर: इस सप्ताह सरसों और प्याज की बुआई के लिए आदर्श समय।",
    ai_analysis_complete: "एआई विश्लेषण पूर्ण",
    close: "बंद करें",
    maximize_income: "अपनी खेती की आय अधिकतम करें",
    estimate_earnings_desc: "वर्तमान लाइव बाजार डेटा और अनुमानित रुझानों के आधार पर अपनी कमाई का अनुमान लगाएं।",
    active_farmers: "सक्रिय किसान",
    market_focus: "बाजार फोकस",
    farming_intel_v1: "खेती खुफिया v1.0",
    wait_rising: "कीमतें बढ़ रही हैं। 2 दिन प्रतीक्षा करें।",
    urgent_sell_desc: "कीमत तेजी से गिर रही है।",
    market_stable_desc: "बाजार स्थिर है।",
    data_provided_by: "मौसम और बाजार खुफिया विभाग द्वारा प्रदान किया गया डेटा।",
    wb_region: "प.ब. क्षेत्र",
  },
  bn: {
    welcome: "AI SATHI-তে আপনাকে স্বাগতম",
    welcome_ai: "নমস্কার! আমি আপনার এআই সাথী। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
    select_language: "আপনার ভাষা নির্বাচন করুন",
    farming: "চাষাবাদ",
    emergency: "জরুরি অবস্থা",
    govt_help: "সরকারি সাহায্য",
    ai_chat: "AI চ্যাট",
    weather: "আবহাওয়া",
    crop_disease: "ফসলের রোগ",
    settings: "সেটিংস",
    medicine_reader: "ওষুধ পাঠক",
    medicine_reader_desc: "নির্দেশ শুনতে ওষুধ স্ক্যান করুন",
    smart_tips: "স্মার্ট টিপস",
    ask_anything: "আমাকে যা খুশি জিজ্ঞাসা করুন...",
    start: "শুরু করুন",
    back: "ফিরে যান",
    home: "হোম",
    offline_mode: "অফলাইন মোড",
    online_mode: "অনলাইন মোড",
    listening: "শুনছি...",
    tap_mic: "কথা বলতে মাইক টিপুন",
    profile: "প্রোফাইল",
    language_label: "ভাষা",
    notifications: "বিজ্ঞপ্তি",
    dark_mode: "ডার্ক মোড",
    privacy: "গোপনীয়তা ও নিরাপত্তা",
    help_about: "সাহায্য ও তথ্য",
    privacy_detail: "আপনার ডেটা আপনার ফোনে থাকে। আমরা আপনার অবস্থান বা পরিচয় শেয়ার করি না। অফলাইন মোড ১০০% গোপনীয়তা নিশ্চিত করে।",
    about_detail: "AI SATHI (কৃষিমিত্র) গ্রামীণ ক্ষমতাবর্ধনের জন্য ডিজাইন করা হয়েছে। এটি ইন্টারনেট ছাড়াই গুরুত্বপূর্ণ চাষাবাদ এবং জরুরি পরামর্শ প্রদান করে।",
    sign_out: "সাইন আউট",
    confirm_sign_out: "আপনি কি নিশ্চিত যে আপনি সাইন আউট করতে চান?",
    scheme_kisan_title: "প্রধানমন্ত্রী কিষাণ নিধি",
    scheme_kisan_desc: "চাষীদের জন্য বার্ষিক ৬,০০০ টাকা",
    scheme_bima_title: "ফসল বীমা যোজনা",
    scheme_bima_desc: "ক্ষতির বিরুদ্ধে ফসল বীমা",
    scheme_kcc_title: "কিষাণ ক্রেডিট কার্ড",
    scheme_kcc_desc: "চাষের জন্য কম সুদে ঋণ",
    contact_police: "পুলিশ ডাকুন",
    contact_police_desc: "১০০ ডায়াল করুন",
    contact_medical: "চিকিৎসা সহায়তা",
    contact_medical_desc: "১০৮ ডায়াল করুন",
    contact_family: "পরিবারের যোগাযোগ",
    contact_family_desc: "পরিবারকে জানান",
    farming_tip_organic_title: "জৈব সার ব্যবহার করুন",
    farming_tip_organic_desc: "মাটির স্বাস্থ্যের ৪০% উন্নতি করে",
    farming_tip_rotation_title: "শস্য আবর্তন",
    farming_tip_rotation_desc: "মাটির পুষ্টির ক্ষয় রোধ করে",
    sos_active: "এস ও এস সক্রিয়। জরুরি পরিচিতিদের জানানো হয়েছে।",
    login_welcome_back: "আবার স্বাগতম",
    login_create_account: "অ্যাকাউন্ট তৈরি করুন",
    login_full_name: "পুরো নাম",
    login_phone_number: "ফোন নম্বর",
    login_password: "ওটিপি / পাসওয়ার্ড",
    login_create_password: "পাসওয়ার্ড তৈরি করুন",
    login_button: "লগইন",
    register_button: "নিবন্ধন",
    login_new_here: "নতুন? অ্যাকাউন্ট তৈরি করুন",
    login_already_have_account: "ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন",
    login_error_password_length: "পাসওয়ার্ড কমপক্ষে ৪টি অক্ষরের হতে হবে",
    login_error_phone_not_registered: "ফোন নম্বর নিবন্ধিত নয়",
    login_error_wrong_password: "ভুল পাসওয়ার্ড",
    login_digital_farming_companion: "আপনার ডিজিটাল চাষাবাদ সঙ্গী",
    login_secure_auth: "সুরক্ষিত অফলাইন-প্রথম প্রমাণীকরণ",
    personalize_experience: "অভিজ্ঞতা ব্যক্তিগতকরণ করুন",
    select_primary_language: "আপনার প্রাথমিক ভাষা নির্বাচন করুন",
    weather_alerts: "আবহাওয়া জরুরি সতর্কতা",
    flood_risk: "বন্যার ঝুঁকি",
    storm_severity: "ঝড়ের তীব্রতা",
    wind_speed: "বাতাসের গতি",
    rain_prob: "বৃষ্টির সম্ভাবনা",
    temp: "তাপমাত্রা",
    humidity: "আর্দ্রতা",
    safe: "নিরাপদ",
    moderate_risk: "মাঝারি ঝুঁকি",
    dangerous: "বিপজ্জনক",
    ai_suggestions: "এআই সুরক্ষা পরামর্শ",
    protect_crops: "আপনার ফসলের সুরক্ষা দিন",
    store_grains: "ফসল ঘরে রাখুন",
    disconnect_irrigation: "সেচ মোটর বন্ধ করুন",
    shelter_livestock: "গবাদি পশু নিরাপদ স্থানে সরান",
    offline_alerts: "অফলাইন মোড: শেষ আপডেট উপলব্ধ",
    heavy_rain_warning: "আগামী ৩ ঘণ্টায় ভারী বৃষ্টির সম্ভাবনা",
    high_wind_warning: "চাষের জমিতে ঝড়ের সতর্কতা",
    flood_warning: "নিচু এলাকায় বন্যার সতর্কতা",
    animal_emergency: "গবাদি পশু জরুরি সহায়তা",
    select_animal: "প্রাণী নির্বাচন করুন",
    cow: "গরু",
    goat: "ছাগল",
    buffalo: "মোষ",
    chicken: "মুরগি",
    describe_symptoms: "লক্ষণগুলি বর্ণনা করুন",
    symptoms_placeholder: "যেমন - খাচ্ছে না, জ্বর, আঘাত...",
    upload_photo: "প্রাণীর ছবি আপলোড করুন",
    analyzing: "AI স্বাস্থ্য বিশ্লেষণ করছে...",
    ai_vet_report: "AI পশু চিকিৎসা রিপোর্ট",
    seriousness: "জরুরি স্তর",
    possible_condition: "সম্ভাব্য সমস্যা",
    first_aid: "প্রাথমিক চিকিৎসা পরামর্শ",
    hydration: "জলীয় খাবার পরামর্শ",
    mild: "সামান্য",
    moderate_level: "মাঝারি",
    critical: "গুরুতর",
    nearby_vet: "নিকটস্থ পশু চিকিৎসা সহায়তা",
    vet_distance: "কিমি দূরে",
    call_vet: "ডাক্তারকে ডাকুন",
    machine_emergency: "মেশিন জরুরি সহায়তা",
    select_machine: "মেশিন নির্বাচন করুন",
    tractor: "ট্যাক্টর",
    pump: "জলের পাম্প",
    motor: "সেচ মোটর",
    harvester: "হারভেস্টার",
    describe_problem: "সমস্যাটি বর্ণনা করুন",
    problem_placeholder: "যেমন - স্টার্ট হচ্ছে না, গরম হচ্ছে, অদ্ভুত শব্দ...",
    troubleshooting: "এআই সমস্যা সমাধানের ধাপ",
    severity_level: "গুরুতর স্তর",
    mechanic_help: "নিকটস্থ মেকানিক সহায়তা",
    call_mechanic: "মেকানিককে ডাকুন",
    not_starting: "স্টার্ট হচ্ছে না",
    overheating: "অতিরিক্ত গরম হওয়া",
    leakage: "লিকেজ",
    unusual_sound: "অদ্ভুত শব্দ",
    low_power: "কম শক্তি",
    machine_fault_critical: "গুরুতর জ্বালানি/তেল লিকেজ বা ইঞ্জিনের ব্যর্থতা",
    machine_fault_medium: "ব্যাটারি/বৈদ্যতিক ত্রুটি বা নোংরা ফিল্টার",
    machine_fault_low: "সাধারণ রক্ষণাবেক্ষণ প্রয়োজন",
    step_turn_off: "অবিলম্বে ইঞ্জিন বন্ধ করুন",
    step_disconnect_battery: "ব্যাটারি টার্মিনাল খুলে ফেলুন",
    step_check_leaks: "জ্বালানি লিকেজ আছে কিনা পরীক্ষা করুন",
    step_no_restart: "আবার চালু করার চেষ্টা করবেন না",
    step_check_fluids: "জ্বালানি/তেলের স্তর পরীক্ষা করুন",
    step_clean_filter: "এয়ার ফিল্টার ইনটেক পরিষ্কার করুন",
    step_check_voltage: "ব্যাটারি ভোল্টেজ সংযোগ পরীক্ষা করুন",
    step_listen_noise: "নির্দিষ্ট শব্দের ধরন শোনার চেষ্টা করুন",
    high_risk: "উচ্চ",
    medium_risk: "মাঝারি",
    low_risk: "নিম্ন",
    market_dashboard: "লাইভ বাজার দর",
    crop_rice: "চাল",
    crop_potato: "আলু",
    crop_wheat: "গম",
    crop_onion: "পিঁয়াজ",
    crop_tomato: "টমেটো",
    crop_mustard: "সরিষা",
    market_demand: "বাজার চাহিদা",
    high_demand: "বেশি চাহিদা",
    stable: "স্থিতিশীল",
    falling: "কমছে",
    urgent_sell: "দ্রুত বিক্রি করুন",
    sell_recommendation: "AI বিক্রয় পরামর্শ",
    profit_estimator: "লাভ ক্যালকুলেটর",
    enter_quantity: "পরিমাণ লিখুন (কেজি)",
    estimated_earnings: "আনুমানিক আয়",
    best_time_to_sell: "বিক্রির সেরা সময়",
    search_crop: "ফসল খুঁজুন...",
    sort_by: "সাজান",
    highest_price: "সর্বোচ্চ দাম",
    biggest_increase: "সবচেয়ে বেশি বৃদ্ধি",
    today_price: "আজকের দাম",
    last_updated: "শেষ আপডেট",
    offline_market: "অফলাইন: সর্বশেষ বাজার দর",
    select_crop: "ফসল নির্বাচন করুন",
    best_time_is: "বিক্রির সেরা মাস: ",
    jan: "জানুয়ারি", feb: "ফেব্রুয়ারি", mar: "মার্চ", apr: "এপ্রিল", may: "মে", jun: "জুন",
    jul: "জুলাই", aug: "আগস্ট", sep: "সেপ্টেম্বর", oct: "অক্টোবর", nov: "নভেম্বর", dec: "ডিসেম্বর",
    crop_doctor: "ফসল ডাক্তার",
    soil_analyzer: "মাটি পরীক্ষক",
    smart_irrigation: "স্মার্ট সেচ",
    pest_alert: "পোকা সতর্কবার্তা",
    farming_calendar: "চাষাবাদ ক্যালেন্ডার",
    smart_tools: "স্মার্ট চাষাবাদ সরঞ্জাম",
    market_intelligence: "বাজার দর ড্যাশবোর্ড",
    tool_doctor_res: "ফসলের অবস্থা: সুস্থ। সামান্য নাইট্রোজেনের অভাব। কম্পোস্ট সার দেওয়ার পরামর্শ।",
    tool_soil_res: "মাটির অবস্থা: দোআঁশ। পিএইচ ৬.৫ (সেরা)। জৈব কার্বন ভালো আছে।",
    tool_irrigation_res: "সেচ পরামর্শ: আজ বাষ্পীভবন কম। সন্ধ্যা ৬টায় জল দেওয়ার সময়।",
    tool_pest_res: "পোকার ঝুঁকি: কম। আর্দ্রতা বেশি, টমেটোতে ছত্রাক লক্ষ্য করুন।",
    tool_calendar_res: "ক্যালেন্ডার: এই সপ্তাহে সরিষা ও পিঁয়াজ বোনার জন্য উপযুক্ত সময়।",
    ai_analysis_complete: "AI বিশ্লেষণ সম্পন্ন",
    close: "বন্ধ করুন",
    maximize_income: "আপনার চাষাবাদের আয় বৃদ্ধি করুন",
    estimate_earnings_desc: "বর্তমান বাজার দর এবং ভবিষ্যতের পূর্বাভাসের ভিত্তিতে আপনার আয়ের হিসাব করুন।",
    active_farmers: "সক্রিয় চাষী",
    market_focus: "বাজার ফোকাস",
    farming_intel_v1: "চাষাবাদ বুদ্ধিমত্তা v1.0",
    wait_rising: "দাম বাড়ছে। ২ দিন অপেক্ষা করুন।",
    urgent_sell_desc: "দাম দ্রুত কমছে।",
    market_stable_desc: "বাজার স্থিতিশীল।",
    data_provided_by: "আবহাওয়া ও বাজার তথ্য বিভাগ দ্বারা প্রদত্ত তথ্য।",
    wb_region: "পঃবংগ অঞ্চল",
  },
  ta: {
    welcome: "AI SATHI-க்கு உங்களை வரவேற்கிறோம்",
    welcome_ai: "வணக்கம்! நான் உங்கள் AI சாதி. இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    select_language: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    farming: "விவசாயம்",
    emergency: "அவசரகாலம்",
    govt_help: "அரசு உதவி",
    ai_chat: "AI அரட்டை",
    weather: "வானிலை",
    crop_disease: "பயிர் நோய்",
    settings: "அமைப்புகள்",
    medicine_reader: "மருந்து படிப்பவர்",
    medicine_reader_desc: "Scan medicine to hear instructions",
    smart_tips: "ஸ்மார்ட் டிப்ஸ்",
    ask_anything: "என்னிடம் எதையும் கேளுங்கள்...",
    start: "தொடங்கு",
    back: "பின்னால்",
    home: "முகப்பு",
    offline_mode: "ஆஃப்லைன் பயன்முறை",
    online_mode: "ஆன்லைன் பயன்முறை",
    listening: "கேட்கிறது...",
    tap_mic: "பேச மைக்ரோஃபோனைத் தட்டவும்",
    profile: "சுயவிவரம்",
    language_label: "மொழி",
    notifications: "அறிவிப்புகள்",
    dark_mode: "இருண்ட பயன்முறை",
    privacy: "தனியுரிமை மற்றும் பாதுகாப்பு",
    help_about: "உதவி மற்றும் தகவல்",
    privacy_detail: "உங்கள் தரவு உங்கள் போனிலேயே இருக்கும். உங்கள் இருப்பிடம் அல்லது அடையாளத்தை நாங்கள் பகிர மாட்டோம். ஆஃப்லைன் பயன்முறை 100% தனியுரிமையை உறுதி செய்கிறது.",
    about_detail: "AI SATHI (கிருஷிமித்ரோ) கிராமப்புற மேம்பாட்டிற்காக வடிவமைக்கப்பட்டுள்ளது. இது இணையம் இல்லாமலேயே முக்கியமான விவசாயம் மற்றும் அவசரகால ஆலோசனைகளை வழங்குகிறது.",
    sign_out: "வெளியேறு",
    confirm_sign_out: "நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
    scheme_kisan_title: "பிஎம்-கிசான் நிதி",
    scheme_kisan_desc: "விவசாயிகளுக்கு ஆண்டுக்கு ₹6,000",
    scheme_bima_title: "பயிர் காப்பீட்டுத் திட்டம்",
    scheme_bima_desc: "இழப்புக்கு எதிரான பயிர் காப்பீடு",
    scheme_kcc_title: "கிசான் கிரெடிட் கார்டு",
    scheme_kcc_desc: "விவசாயத்திற்கு குறைந்த வட்டி கடன்",
    contact_police: "போலீசை அழைக்கவும்",
    contact_police_desc: "100 ஐ அழைக்கவும்",
    contact_medical: "மருத்துவ உதவி",
    contact_medical_desc: "108 ஐ அழைக்கவும்",
    contact_family: "குடும்ப தொடர்பு",
    contact_family_desc: "குடும்பத்திற்கு தெரிவிக்கவும்",
    farming_tip_organic_title: "இயற்கை உரத்தைப் பயன்படுத்துங்கள்",
    farming_tip_organic_desc: "மண் ஆரோக்கியத்தை 40% மேம்படுத்துகிறது",
    farming_tip_rotation_title: "பயிர் சுழற்சி",
    farming_tip_rotation_desc: "மண் ஊட்டச்சத்து குறைபாட்டைத் தடுக்கிறது",
    sos_active: "SOS செயல்படுத்தப்பட்டது. அவசர தொடர்புகளுக்கு தெரிவிக்கப்பட்டது.",
    login_welcome_back: "மீண்டும் வருக",
    login_create_account: "கணக்கை உருவாக்கு",
    login_full_name: "முழு பெயர்",
    login_phone_number: "தொலைபேசி எண்",
    login_password: "OTP / கடவுச்சொல்",
    login_create_password: "கடவுச்சொல்லை உருவாக்கு",
    login_button: "உள்நுழை",
    register_button: "பதிவு செய்",
    login_new_here: "புதியவரா? கணக்கை உருவாக்குங்கள்",
    login_already_have_account: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்",
    login_error_password_length: "கடவுச்சொல் குறைந்தது 4 எழுத்துகளாக இருக்க வேண்டும்",
    login_error_phone_not_registered: "தொலைபேசி எண் பதிவு செய்யப்படவில்லை",
    login_error_wrong_password: "தவறான கடவுச்சொல்",
    login_digital_farming_companion: "உங்கள் டிஜிட்டல் விவசாய துணை",
    login_secure_auth: "பாதுகாப்பான ஆஃப்லைன்-முதல் அங்கீகாரம்",
    personalize_experience: "அனுபவத்தைத் தனிப்பயனாக்கு",
    select_primary_language: "உங்கள் முதன்மை மொழியைத் தேர்ந்தெடுக்கவும்",
    weather_alerts: "வானிலை அவசர எச்சரிக்கைகள்",
    flood_risk: "வெள்ள அபாயம்",
    storm_severity: "புயல் தீவிரம்",
    wind_speed: "காற்றின் வேகம்",
    rain_prob: "மழைக்கான வாய்ப்பு",
    temp: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    safe: "பாதுகாப்பானது",
    moderate_risk: "மிதமான அபாயம்",
    dangerous: "ஆபத்தானது",
    ai_suggestions: "AI பாதுகாப்பு பரிந்துரைகள்",
    protect_crops: "பயிர்களைப் பாதுகாக்கவும்",
    store_grains: "தானியங்களை வீட்டுக்குள் வைக்கவும்",
    disconnect_irrigation: "மின்சார மோட்டார்களை அணைக்கவும்",
    shelter_livestock: "கால்நடைகளை மேடான இடத்திற்கு மாற்றவும்",
    offline_alerts: "ஆஃப்லைன்: கடைசியாக புதுப்பிக்கப்பட்ட தகவல்",
    heavy_rain_warning: "3 மணிநேரத்தில் பலத்த மழை பெய்யக்கூடும்",
    high_wind_warning: "பலத்த காற்று வீசக்கூடும்",
    flood_warning: "வெள்ள எச்சரிக்கை விடப்பட்டுள்ளது",
    animal_emergency: "கால்நடை அவசர உதவி",
    select_animal: "விலங்கைத் தேர்ந்தெடுக்கவும்",
    cow: "பசு",
    goat: "ஆடு",
    buffalo: "எருமை",
    chicken: "கோழி",
    describe_symptoms: "அறிகுறிகளை விவரிக்கவும்",
    symptoms_placeholder: "எ.கா. சாப்பிடவில்லை, காய்ச்சல், காயம்...",
    upload_photo: "விலங்கின் புகைப்படத்தைப் பதிவேற்றவும்",
    analyzing: "AI ஆரோக்கியத்தை ஆய்வு செய்கிறது...",
    ai_vet_report: "AI கால்நடை மருத்துவ அறிக்கை",
    seriousness: "அவசர நிலை",
    possible_condition: "சாத்தியமான பாதிப்பு",
    first_aid: "முதலுதவி ஆலோசனை",
    hydration: "நீர்ச்சத்து ஆலோசனை",
    mild: "லேசானது",
    moderate_level: "மிதமானது",
    critical: "தீவிரமானது",
    nearby_vet: "அருகிலுள்ள கால்நடை உதவி",
    vet_distance: "கி.மீ தூரத்தில்",
    call_vet: "மருத்துவரை அழைக்கவும்",
    machine_emergency: "இயந்திர அவசர உதவி",
    select_machine: "இயந்திரத்தைத் தேர்ந்தெடு",
    tractor: "டிராக்டர்",
    pump: "தண்ணீர் பம்ப்",
    motor: "மின்சார மோட்டார்",
    harvester: "அறுவடை இயந்திரம்",
    describe_problem: "பிரச்சினையை விவரிக்கவும்",
    problem_placeholder: "எ.கா. ஸ்டார்ட் ஆகவில்லை, சூடாகிறது, சத்தம் வருகிறது...",
    troubleshooting: "AI பழுதுபார்க்கும் படிகள்",
    severity_level: "தீவிர நிலை",
    mechanic_help: "அருகிலுள்ள மெக்கானிக்",
    call_mechanic: "மெக்கனிக்கை அழைக்கவும்",
    not_starting: "ஸ்டார்ட் ஆகவில்லை",
    overheating: "அதிக வெப்பம்",
    leakage: "கசிவு",
    unusual_sound: "அசாதாரண சத்தம்",
    low_power: "குறைந்த சக்தி",
    machine_fault_critical: "முக்கிய எரிபொருள்/எண்ணெய் கசிவு அல்லது என்ஜின் பழுது",
    machine_fault_medium: "பேட்டரி/மின்சார கோளாறு அல்லது அடைக்கப்பட்ட வடிகட்டி",
    machine_fault_low: "பொதுவான பராமரிப்பு தேவை",
    step_turn_off: "என்ஜினை உடனடியாக அணைக்கவும்",
    step_disconnect_battery: "பேட்டரி முனையங்களைத் துண்டிக்கவும்",
    step_check_leaks: "எரிபொருள் கசிவு உள்ளதா என சரிபார்க்கவும்",
    step_no_restart: "மீண்டும் இயக்க முயற்சிக்க வேண்டாம்",
    step_check_fluids: "எரிபொருள்/எண்ணெய் அளவை சரிபார்க்கவும்",
    step_clean_filter: "ஏர் பில்டரை சுத்தம் செய்யவும்",
    step_check_voltage: "பேட்டரி மின்னழுத்தத்தை சரிபார்க்கவும்",
    step_listen_noise: "சத்தத்தின் தன்மையை கவனிக்கவும்",
    high_risk: "அதிக",
    medium_risk: "நடுத்தர",
    low_risk: "குறைந்த",
    market_dashboard: "நேரடி சந்தை விலை",
    crop_rice: "அரிசி",
    crop_potato: "உருளைக்கிழங்கு",
    crop_wheat: "கோதுமை",
    crop_onion: "வெங்காயம்",
    crop_tomato: "தக்காளி",
    crop_mustard: "கடுகு",
    market_demand: "சந்தை தேவை",
    high_demand: "அதிக தேவை",
    stable: "நிலையானது",
    falling: "வீழ்ச்சி",
    urgent_sell: "உடனடியாக விற்கவும்",
    sell_recommendation: "AI விற்பனை ஆலோசனை",
    profit_estimator: "லாப மதிப்பீட்டாளர்",
    enter_quantity: "அளவு (கிலோ)",
    estimated_earnings: "மதிப்பிடப்பட்ட வருமானம்",
    best_time_to_sell: "விற்க சிறந்த நேரம்",
    search_crop: "பயிரைத் தேடுங்கள்...",
    sort_by: "வரிசைப்படுத்து",
    highest_price: "அதிகபட்ச விலை",
    biggest_increase: "அதிகபட்ச உயர்வு",
    today_price: "இன்றைய விலை",
    last_updated: "கடைசி புதுப்பிப்பு",
    offline_market: "ஆஃப்லைன்: கடைசியாக புதுப்பிக்கப்பட்டது",
    select_crop: "பயிரைத் தேர்ந்தெடுக்கவும்",
    best_time_is: "விற்க சிறந்த மாதம்: ",
    jan: "ஜனவரி", feb: "பிப்ரவரி", mar: "மார்ச்", apr: "ஏப்ரல்", may: "மே", jun: "ஜூன்",
    jul: "ஜூலை", aug: "ஆகஸ்ட்", sep: "செப்டம்பர்", oct: "அக்டோபர்", nov: "நவம்பர்", dec: "டிசம்பர்",
    crop_doctor: "பயிர் மருத்துவர்",
    soil_analyzer: "மண் ஆய்வாளர்",
    smart_irrigation: "ஸ்மார்ட் பாசனம்",
    pest_alert: "பூச்சி எச்சரிக்கை",
    farming_calendar: "விவசாய நாட்காட்டி",
    smart_tools: "ஸ்மார்ட் விவசாய கருவிகள்",
    market_intelligence: "சந்தை நுண்ணறிவு மேடை",
    tool_doctor_res: "பயிர் ஆரோக்கியம்: ஆரோக்கியமானது. நைட்ரஜன் குறைபாடு உள்ளது. உரம் சேர்க்கவும்.",
    tool_soil_res: "மண் நிலை: வண்டல் மண். pH 6.5 (சிறந்தது). கரிம கார்பன் நன்றாக உள்ளது.",
    tool_irrigation_res: "பாசன குறிப்பு: இன்று ஆவியாதல் குறைவு. மாலை 6:00 மணிக்கு தண்ணீர் பாய்ச்சவும்.",
    tool_pest_res: "பூச்சி அபாயம்: குறைவு. ஈரப்பதம் அதிகம், தக்காளியில் பூஞ்சை வளர்ச்சியை கவனிக்கவும்.",
    tool_calendar_res: "நாட்காட்டி: இந்த வாரம் கடுகு மற்றும் வெங்காயம் விதைக்க ஏற்றது.",
    ai_analysis_complete: "AI பகுப்பாய்வு முடிந்தது",
    close: "மூடு",
    maximize_income: "உங்கள் விவசாய வருவாயை அதிகரிக்கவும்",
    estimate_earnings_desc: "சந்தையின் தற்போதைய நிலையை வைத்து உங்கள் வருவாயை மதிப்பிடுங்கள்.",
    active_farmers: "செயலில் உள்ள விவசாயிகள்",
    market_focus: "சந்தை கவனம்",
    farming_intel_v1: "விவசாய நுண்ணறிவு v1.0",
    wait_rising: "விலை உயர்கிறது. 2 நாட்கள் காத்திருக்கவும்.",
    urgent_sell_desc: "விலை வேகமாக குறைகிறது.",
    market_stable_desc: "சந்தை சீராக உள்ளது.",
    data_provided_by: "வானிலை மற்றும் சந்தை நுண்ணறிவுத் துறையால் வழங்கப்பட்ட தரவு.",
    wb_region: "WB மண்டலம்",
  },
  te: {
    welcome: "AI SATHI కి మీకు స్వాగతం",
    welcome_ai: "నమస్కారం! నేను మీ AI సాథిని. ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?",
    select_language: "మీ భాషను ఎంచుకోండి",
    farming: "వ్యవసాయం",
    emergency: "అత్యవసర పరిస్థితి",
    govt_help: "ప్రభుత్వ సహాయం",
    ai_chat: "AI చాట్",
    weather: "వాతావరణం",
    crop_disease: "పంట వ్యాధి",
    settings: "సెట్టింగులు",
    medicine_reader: "మందుల రీడర్",
    medicine_reader_desc: "Scan medicine to hear instructions",
    smart_tips: "స్మార్ట్ చిట్కాలు",
    ask_anything: "నన్ను ఏదైనా అడగండి...",
    start: "ప్రారంభించండి",
    back: "వెనుకకు",
    home: "హోమ్",
    offline_mode: "ఆఫ్‌లైన్ మోడ్",
    online_mode: "ఆన్‌లైన్ మోడ్",
    listening: "వింటున్నాను...",
    tap_mic: "మాట్లాడటానికి మైక్ నొక్కండి",
    profile: "ప్రొఫైల్",
    language_label: "భాష",
    notifications: "నోటిఫికేషన్లు",
    dark_mode: "డార్క్ మోడ్",
    privacy: "గోప్యత మరియు భద్రత",
    help_about: "సహాయం మరియు సమాచారం",
    privacy_detail: "మీ డేటా మీ ఫోన్‌లోనే ఉంటుంది. మేము మీ లొకేషన్ లేదా గుర్తింపును పంచుకోము. ఆఫ్‌లైన్ మోడ్ 100% గోప్యతను నిర్ధారిస్తుంది.",
    about_detail: "AI SATHI (కృషిమిత్రో) గ్రామీణ సాధికారత కోసం రూపొందించబడింది. ఇది ఇంటర్నెట్ లేకుండానే కీలకమైన వ్యవసాయ మరియు అత్యవసర సలహాలను అందిస్తుంది.",
    sign_out: "సైన్ అవుట్",
    confirm_sign_out: "మీరు ఖచ్చితంగా సైన్ అవుట్ చేయాలనుకుంటున్నారా?",
    scheme_kisan_title: "పీఎం-కిసాన్ నిధి",
    scheme_kisan_desc: "రైతులకు ఏటా ₹6,000",
    scheme_bima_title: "ఫసల్ బీమా యోజన",
    scheme_bima_desc: "నష్టంపై పంట బీమా",
    scheme_kcc_title: "కిసాన్ క్రెడిట్ కార్డ్",
    scheme_kcc_desc: "వ్యవసాయానికి తక్కువ వడ్డీ రుణాలు",
    contact_police: "పోలీసులకు కాల్ చేయండి",
    contact_police_desc: "100 డయల్ చేయండి",
    contact_medical: "వైద్య సహాయం",
    contact_medical_desc: "108 డయల్ చేయండి",
    contact_family: "కుటుంబ సంప్రదింపు",
    contact_family_desc: "కుటుంబానికి తెలియజేయండి",
    farming_tip_organic_title: "సేంద్రీయ ఎరువును వాడండి",
    farming_tip_organic_desc: "నేల ఆరోగ్యాన్ని 40% మెరుగుపరుస్తుంది",
    farming_tip_rotation_title: "పంట మార్పిడి",
    farming_tip_rotation_desc: "నేల పోషకాల క్షీణతను నివారిస్తుంది",
    sos_active: "SOS యాక్టివేట్ చేయబడింది. అత్యవసర పరిచయాలకు సమాచారం అందించబడింది.",
    login_welcome_back: "మళ్ళీ స్వాగతం",
    login_create_account: "ఖాతాను సృష్టించండి",
    login_full_name: "పూర్తి పేరు",
    login_phone_number: "ఫోన్ నంబర్",
    login_password: "OTP / పాస్‌వర్డ్",
    login_create_password: "పాస్‌వర్డ్‌ను సృష్టించండి",
    login_button: "లాగిన్",
    register_button: "నమోదు",
    login_new_here: "కొత్తవారా? ఖాతాను సృష్టించండి",
    login_already_have_account: "ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి",
    login_error_password_length: "పాస్‌వర్డ్ కనీసం 4 అక్షరాలు ఉండాలి",
    login_error_phone_not_registered: "ఫోన్ నంబర్ నమోదు కాలేదు",
    login_error_wrong_password: "తప్పు పాస్‌వర్డ్",
    login_digital_farming_companion: "మీ డిజిటల్ వ్యవసాయ సహచరుడు",
    login_secure_auth: "సురక్షితమైన ఆఫ్‌లైన్-మొదటి ప్రమాణీకరణ",
    personalize_experience: "అనుభవాన్ని వ్యక్తిగతీకరించండి",
    select_primary_language: "దయచేసి మీ ప్రాథమిక భాషను ఎంచుకోండి",
    weather_alerts: "వాతావరణ అత్యవసర హెచ్చరికలు",
    flood_risk: "వరద ముప్పు",
    storm_severity: "తుపాను తీవ్రత",
    wind_speed: "గాలి వేగం",
    rain_prob: "వర్షం పడే అవకాశం",
    temp: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    safe: "సురక్షితం",
    moderate_risk: "మధ్యస్థ ముప్పు",
    dangerous: "ప్రమాదకరం",
    ai_suggestions: "AI భద్రతా సూచనలు",
    protect_crops: "మీ పంటలను రక్షించుకోండి",
    store_grains: "ధాన్యాన్ని ఇంట్లో భద్రపరచండి",
    disconnect_irrigation: "మోటార్లను ఆపివేయండి",
    shelter_livestock: "పశువులను సురక్షిత ప్రాంతాలకు తరలించండి",
    offline_alerts: "ఆఫ్‌లైన్: పాత సమాచారం అందుబాటులో ఉంది",
    heavy_rain_warning: "3 గంటల్లో భారీ వర్షం పడే అవకాశం",
    high_wind_warning: "తీవ్రమైన గాలి హెచ్చరిక",
    flood_warning: "వరద హెచ్చరిక జారీ చేయబడింది",
    animal_emergency: "పశువుల అత్యవసర సహాయం",
    select_animal: "జంతువును ఎంచుకోండి",
    cow: "ఆవు",
    goat: "మేక",
    buffalo: "గేదె",
    chicken: "కోడి",
    describe_symptoms: "లక్షణాలను వివరించండి",
    symptoms_placeholder: "ఉదా. తినకపోవడం, జ్వరం, గాయం...",
    upload_photo: "జంతువు ఫోటో అప్‌లోడ్ చేయండి",
    analyzing: "AI ఆరోగ్యాన్ని విశ్లేషిస్తోంది...",
    ai_vet_report: "AI పశువైద్య నివేదిక",
    seriousness: "అత్యవసర స్థాయి",
    possible_condition: "సాధ్యమయ్యే సమస్య",
    first_aid: "ప్రథమ చికిత్స సలహా",
    hydration: "హైడ్రేషన్ సలహా",
    mild: "తక్కువ",
    moderate_level: "మధ్యస్థం",
    critical: "తీవ్రమైనది",
    nearby_vet: "దగ్గరలోని పశువైద్య సహాయం",
    vet_distance: "కి.మీ దూరంలో",
    call_vet: "డాక్టర్‌ని పిలవండి",
    machine_emergency: "యంత్ర అత్యవసర సహాయం",
    select_machine: "యంత్రాన్ని ఎంచుకోండి",
    tractor: "ట్రాక్టర్",
    pump: "వాటర్ పంప్",
    motor: "మోటార్",
    harvester: "హార్వెస్టర్",
    describe_problem: "సమస్యను వివరించండి",
    problem_placeholder: "ఉదా. స్టార్ట్ కావట్లేదు, వేడెక్కుతోంది, వింత శబ్దం...",
    troubleshooting: "AI మరమ్మతు సూచనలు",
    severity_level: "తీవ్రత స్థాయి",
    mechanic_help: "దగ్గరలోని మెకానిక్",
    call_mechanic: "మెకానిక్ ని పిలవండి",
    not_starting: "స్టార్ట్ కావట్లేదు",
    overheating: "వేడెక్కడం",
    leakage: "లీకేజీ",
    unusual_sound: "వింత శబ్దం",
    low_power: "తక్కువ శక్తి",
    machine_fault_critical: "తీవ్రమైన ఇంధన/నూనె లీకేజీ లేదా ఇంజిన్ వైఫల్యం",
    machine_fault_medium: "బ్యాటరీ/విద్యుత్ లోపం లేదా మూసుకుపోయిన ఫిల్టర్",
    machine_fault_low: "సాధారణ మరమ్మత్తు అవసరం",
    step_turn_off: "ఇంజిన్‌ను వెంటనే ఆపివేయండి",
    step_disconnect_battery: "బ్యాటరీ టెర్మినల్స్‌ను తొలగించండి",
    step_check_leaks: "మంటలు చెలరేగే లీకేజీలను తనిఖీ చేయండి",
    step_no_restart: "మళ్ళీ స్టార్ట్ చేయడానికి ప్రయత్నించవద్దు",
    step_check_fluids: "ఇంధన/నూనె స్థాయిలను తనిఖీ చేయండి",
    step_clean_filter: "ఎయిర్ ఫిల్టర్‌ను శుభ్రం చేయండి",
    step_check_voltage: "బ్యాటరీ వోల్టేజీని తనిఖీ చేయండి",
    step_listen_noise: "శబ్దం రకాన్ని గమనించండి",
    high_risk: "అధిక",
    medium_risk: "మధ్యస్థ",
    low_risk: "తక్కువ",
    market_dashboard: "లైవ్ మార్కెట్ ధరలు",
    crop_rice: "వరి",
    crop_potato: "బంగాళదుంప",
    crop_wheat: "గోధుమ",
    crop_onion: "ఉల్లిపాయ",
    crop_tomato: "టమోటా",
    crop_mustard: "ఆవాలు",
    market_demand: "మార్కెట్ డిమాండ్",
    high_demand: "ఎక్కువ డిమాండ్",
    stable: "స్థిరంగా",
    falling: "తగ్గుతోంది",
    urgent_sell: "వెంటనే అమ్మండి",
    sell_recommendation: "AI అమ్మకపు సూచన",
    profit_estimator: "లాభాల అంచనా",
    enter_quantity: "పరిమాణాన్ని నమోదు చేయండి (కేజీ)",
    estimated_earnings: "అంచనా వేసిన ఆదాయం",
    best_time_to_sell: "అమ్మడానికి ఉత్తమ సమయం",
    search_crop: "పంటను వెతకండి...",
    sort_by: "క్రమబద్ధీకరించు",
    highest_price: "అత్యధిక ధర",
    biggest_increase: "అత్యధిక పెరుగుదల",
    today_price: "నేటి ధర",
    last_updated: "చివరి అప్‌డేట్",
    offline_market: "ఆఫ్‌లైన్: పాత ధరలు",
    select_crop: "పంటను ఎంచుకోండి",
    best_time_is: "అమ్మడానికి ఉత్తమ నెల: ",
    jan: "జనవరి", feb: "ఫిబ్రవరి", mar: "మార్చి", apr: "ఏప్రిల్", may: "మే", jun: "జూన్",
    jul: "జూలై", aug: "ఆగస్టు", sep: "సెప్టెంబర్", oct: "అక్టోబర్", nov: "నవంబర్", dec: "డిసెంబర్",
    crop_doctor: "పంట డాక్టర్",
    soil_analyzer: "నేల విశ్లేషణ",
    smart_irrigation: "స్మార్ట్ సాగు",
    pest_alert: "కీటకాల హెచ్చరిక",
    farming_calendar: "వ్యవసాయ క్యాలెండర్",
    smart_tools: "స్మార్ట్ వ్యవసాయ పరికరాలు",
    market_intelligence: "మార్కెట్ ఇంటెలిజెన్స్ డ్యాష్‌బోర్డ్",
    tool_doctor_res: "పంట ఆరోగ్యం: బాగుంది. నత్రజని లోపం ఉంది. కంపోస్ట్ వాడండి.",
    tool_soil_res: "నేల పరిస్థితి: లోమీ. pH 6.5 (ఉత్తమం). ఆర్గానిక్ కార్బన్ బాగుంది.",
    tool_irrigation_res: "సాగు చిట్కా: ఈరోజు నీటి ఆవిరి తక్కువ. సాయంత్రం 6:00 గంటలకు నీరు పెట్టండి.",
    tool_pest_res: "కీటకాల ముప్పు: తక్కువ. తేమ ఎక్కువగా ఉంది, టమోటాలో ఫంగస్ జాగ్రత్త.",
    tool_calendar_res: "క్యాలెండర్: ఈ వారం ఆవాలు మరియు ఉల్లిపాయలు నాటడానికి అనువైనది.",
    ai_analysis_complete: "AI విశ్లేషణ పూర్తయింది",
    close: "మూసివేయి",
    maximize_income: "మీ వ్యవసాయ ఆదాయాన్ని పెంచుకోండి",
    estimate_earnings_desc: "మార్కెట్ ధరల ఆధారంగా మీ సంపాదనను అంచనా వేయండి.",
    active_farmers: "చురుకైన రైతులు",
    market_focus: "మార్కెట్ దృష్టి",
    farming_intel_v1: "వ్యవసాయ ఇంటెలిజెన్స్ v1.0",
    wait_rising: "ధరలు పెరుగుతున్నాయి. 2 రోజులు ఆగండి.",
    urgent_sell_desc: "ధరలు వేగంగా తగ్గుతున్నాయి.",
    market_stable_desc: "మార్కెట్ స్థిరంగా ఉంది.",
    data_provided_by: "వాతావరణ మరియు మార్కెట్ ఇంటెలిజెన్స్ విభాగం సమాచారం.",
    wb_region: "WB ప్రాంతం",
  },
  mr: {
    welcome: "AI SATHI मध्ये तुमचे स्वागत आहे",
    welcome_ai: "नमस्कार! मी तुमचा एआय साथी आहे. आज मी तुम्हाला कशी मदत करू शकतो?",
    select_language: "तुमची भाषा निवडा",
    farming: "शेती",
    emergency: "आणीबाणी",
    govt_help: "सरकारी मदत",
    ai_chat: "AI चॅट",
    weather: "हवामान",
    crop_disease: "पीक रोग",
    settings: "सेटिंग्स",
    medicine_reader: "औषध वाचक",
    medicine_reader_desc: "सूचना ऐकण्यासाठी औषध स्कॅन करा",
    smart_tips: "स्मार्ट टिप्स",
    ask_anything: "मला काहीही विचारा...",
    start: "सुरू करा",
    back: "मागे",
    home: "होम",
    offline_mode: "ऑफलाइन मोड",
    online_mode: "ऑनलाइन मोड",
    listening: "ऐकत आहे...",
    tap_mic: "बोलण्यासाठी माइक दाबा",
    profile: "प्रोफाईल",
    language_label: "भाषा",
    notifications: "सूचना",
    dark_mode: "डार्क मोड",
    privacy: "गोपनीयता आणि सुरक्षा",
    help_about: "मदत आणि माहिती",
    privacy_detail: "तुमचा डेटा तुमच्या phone वरच राहतो. आम्ही तुमचे location किंवा ओळख शेअर करत नाही. ऑफलाइन मोड १००% गोपनीयता सुनिश्चित करतो।",
    about_detail: "AI SATHI (कृषिमित्रो) ग्रामीण सक्षमीकरणासाठी डिझाइन केले आहे. हे इंटरनेटशिवाय महत्त्वाची शेती आणि आणीबाणीचा सल्ला प्रदान करते.",
    sign_out: "साइन आउट",
    confirm_sign_out: "तुम्हाला खात्री आहे की तुम्ही साइन आउट करू इच्छिता?",
    scheme_kisan_title: "पीएम-किसान निधी",
    scheme_kisan_desc: "शेतकऱ्यांसाठी वार्षिक ₹६,০০০",
    scheme_bima_title: "फसल विमा योजना",
    scheme_bima_desc: "नुकसानीविरुद्ध पीक विमा",
    scheme_kcc_title: "किसान क्रेडिट कार्ड",
    scheme_kcc_desc: "शेतीसाठी कमी व्याजाचे कर्ज",
    contact_police: "पोलिसांना फोन करा",
    contact_police_desc: "100 डायल करा",
    contact_medical: "वैद्यकीय मदत",
    contact_medical_desc: "108 डायल करा",
    contact_family: "कुटुंब संपर्क",
    contact_family_desc: "कुटुंबाला कळवा",
    farming_tip_organic_title: "सेंद्रिय खत वापरा",
    farming_tip_organic_desc: "मातीच्या आरोग्यात ४०% सुधारणा होते",
    farming_tip_rotation_title: "पीक फेरपालट",
    farming_tip_rotation_desc: "मातीतील पोषक तत्वांचा ऱ्हास रोखते",
    sos_active: "SOS सक्रिय झाले. आणीबाणीच्या संपर्कांना सूचित केले.",
    login_welcome_back: "परत स्वागत आहे",
    login_create_account: "खाते तयार करा",
    login_full_name: "पूर्ण नाव",
    login_phone_number: "फोन नंबर",
    login_password: "OTP / पासवर्ड",
    login_create_password: "पासवर्ड तयार करा",
    login_button: "लॉगिन",
    register_button: "नोंదणी करा",
    login_new_here: "नवीन आहात? खाते तयार करा",
    login_already_have_account: "आधीच खाते आहे? लॉगिन करा",
    login_error_password_length: "पासवर्ड किमान ४ अक्षरांचा असावा",
    login_error_phone_not_registered: "फोन नंबर नोंदणीकृत नाही",
    login_error_wrong_password: "चुकीचा पासवर्ड",
    login_digital_farming_companion: "तुमचा डिजिटल शेती साथीदार",
    login_secure_auth: "सुरक्षित ऑफलाइन-प्रथम प्रमाणीकरण",
    personalize_experience: "अनुभव वैयक्तिकृत करा",
    select_primary_language: "कृपया तुमची प्राथमिक भाषा निवडा",
    weather_alerts: "हवामान आणीबाणी सूचना",
    flood_risk: "पुराचा धोका",
    storm_severity: "वादळाची तीव्रता",
    wind_speed: "वाऱ्याचा वेग",
    rain_prob: "पावसाची शक्यता",
    temp: "तापमान",
    humidity: "आर्द्रता",
    safe: "सुरक्षित",
    moderate_risk: "मध्यम धोका",
    dangerous: "धોకాदायक",
    ai_suggestions: "AI सुरक्षा सल्ला",
    protect_crops: "पिकांचे संरक्षण करा",
    store_grains: "धान्य घरात ठेवा",
    disconnect_irrigation: "सिंचন मोटर बंद करा",
    shelter_livestock: "पशूंना सुरक्षित ठिकाणी हलवा",
    offline_alerts: "ऑफलाइन: शेवटची अपडेट उपलब्ध",
    heavy_rain_warning: "पुढील ३ तासांत मुसळधार पाऊस",
    high_wind_warning: "वेगवान వాऱ्याचा इशारा",
    flood_warning: "पुराचा इशारा जारी",
    animal_emergency: "पशुवैद्यकीय आणीबाणी मदत",
    select_animal: "प्राणी निवडा",
    cow: "गाय",
    goat: "शेळी",
    buffalo: "म्हैस",
    chicken: "कोंबडी",
    describe_symptoms: "लक्षणांचे वर्णन करा",
    symptoms_placeholder: "उदा. खात नाही, ताप, जखम...",
    upload_photo: "प्राण्याचे छायाचित्र अपलोड करा",
    analyzing: "AI आरोग्याचे विश्लेषण करत आहे...",
    ai_vet_report: "AI पशुवैद्यकीय अहवाल",
    seriousness: "आणीबाणी पातळी",
    possible_condition: "संभाव्य समस्या",
    first_aid: "প্রথমোপচার सल्ला",
    hydration: "हायड्रेशन सल्ला",
    mild: "सौम्य",
    moderate_level: "मध्यम",
    critical: "गंभीर",
    nearby_vet: "जवळपासची पशुवैद्यकीय मदत",
    vet_distance: "किमी लांब",
    call_vet: "डॉक्टरांना बोलवा",
    machine_emergency: "यंत्र आणीबाणी मदत",
    select_machine: "यंत्र निवडा",
    tractor: "ट्रॅक्टर",
    pump: "पाण्याचा पंप",
    motor: "सिंचन मोटर",
    harvester: "हार्वेस्टर",
    describe_problem: "समस्येचे वर्णन करा",
    problem_placeholder: "उदा. सुरू होत नाही, गरम होत आहे, विचित्र आवाज...",
    troubleshooting: "AI दोषनिवारण पायऱ्या",
    severity_level: "गंभीरता पातळी",
    mechanic_help: "जवळपासची मेकॅनिक मदत",
    call_mechanic: "मेकॅनिकला बोलवा",
    not_starting: "सुरू होत नाही",
    overheating: "ओव्هرहीटिंग (जास्त गरम होणे)",
    leakage: "ळिकेज",
    unusual_sound: "विचित्र आवाज",
    low_power: "कमी शक्ती",
    machine_fault_critical: "गंभीर इंधन/तेल गळती किंवा इंजिन बिघाड",
    machine_fault_medium: "बॅटरी/इलेक्ट्रिकल दोष किंवा ब्लॉक केलेले फिल्टर",
    machine_fault_low: "सामान्य देखभाल आवश्यक",
    step_turn_off: "इंजिन त्वरित बंद करा",
    step_disconnect_battery: "बॅटरी टर्मिनल डिस्कनेक्ट करा",
    step_check_leaks: "ज्वलनशील द्रव गळती तपासा",
    step_no_restart: "पुन्हा सुरू करण्याचा प्रयत्न करू नका",
    step_check_fluids: "इंधन/तेल पातळी तपासा",
    step_clean_filter: "एयर फिल्टर स्वच्छ करा",
    step_check_voltage: "बॅटरी व्हోల్टेज తपासा",
    step_listen_noise: "विशिष्ट आवाजाचा पॅटर्न ऐका",
    high_risk: "उच्च",
    medium_risk: "मध्यम",
    low_risk: "कमी",
    market_dashboard: "थेट बाजार भाव",
    crop_rice: "तांदूळ",
    crop_potato: "बटाटा",
    crop_wheat: "गहू",
    crop_onion: "कांदा",
    crop_tomato: "टोमॅটো",
    crop_mustard: "मोहरी",
    market_demand: "बाजार मागणी",
    high_demand: "जास्त मागणी",
    stable: "स्थिर",
    falling: "घटत आहे",
    urgent_sell: "त्वरीत विक्री करा",
    sell_recommendation: "AI विक्री सल्ला",
    profit_estimator: "नफा अंदाजक",
    enter_quantity: "प्रमाण टाका (किग्रॅ)",
    estimated_earnings: "अंदाजपत्रकीय कमाई",
    best_time_to_sell: "विक्रीसाठी सर्वोत्तम वेळ",
    search_crop: "पीक शोधा...",
    sort_by: "क्रमवारी लावा",
    highest_price: "उच्चतम किंमत",
    biggest_increase: "सर्वात मोठी वाढ",
    today_price: "आजचा भाव",
    last_updated: "शेवटचे अपडेट",
    offline_market: "ऑफलाइन: शेवटचे भाव",
    select_crop: "पीक निवडा",
    best_time_is: "विक्रीसाठी सर्वोत्तम महिना: ",
    jan: "जानेवारी", feb: "फेब्रुवारी", mar: "मार्च", apr: "एप्रिल", may: "मे", jun: "जून",
    jul: "जुलै", aug: "ऑगस्ट", sep: "सप्टेंबर", oct: "ऑक्टोबर", nov: "नोव्हेंबर", dec: "डिसेंबर",
    crop_doctor: "पीक डॉक्टर",
    soil_analyzer: "माती विश्लेषक",
    smart_irrigation: "स्मार्ट सिंचन",
    pest_alert: "कीड इशारा",
    farming_calendar: "शेती कॅलेंडर",
    smart_tools: "स्मार्ट शेती साधने",
    market_intelligence: "बाजार माहिती डॅशबोर्ड",
    tool_doctor_res: "पीक आरोग्य: निरोगी. नायट्रोजनची थोडी कमतरता. खत घालण्याचा सल्ला.",
    tool_soil_res: "मातीची स्थिती: लोमी. pH 6.5 (उत्तम). सेंद्रिय कार्बन चांगले आहे.",
    tool_irrigation_res: "सिंचन टीप: आज बाष्पीभवन कमी आहे. संध्याकाळी 6:00 वाजता पाणी द्या.",
    tool_pest_res: "कीड धोका: कमी. आर्द्रता जास्त आहे, टोमॅटोमध्ये बুরशी तपासा.",
    tool_calendar_res: "कॅलेंडर: या आठवड्यात मोहरी आणि कांदा पेरणीसाठी उत्तम वेळ.",
    ai_analysis_complete: "AI विश्लेषण पूर्ण झाले",
    close: "बंद करा",
    maximize_income: "तुमचे शेती उत्पन्न वाढवा",
    estimate_earnings_desc: "बाजार दरांच्या आधारे तुमच्या कमाईचा अंदाज घ्या.",
    active_farmers: "सक्रिय शेतकरी",
    market_focus: "बाजार फोकस",
    farming_intel_v1: "शेती बुद्धिमत्ता v1.0",
    wait_rising: "किंमती वाढत आहेत. 2 दिवस थांबा.",
    urgent_sell_desc: "किंमत वेगाने घसरत आहे.",
    market_stable_desc: "बाजार स्थिर आहे.",
    data_provided_by: "हवामान आणि बाजार माहिती विभागाद्वारे प्रदान केलेली माहिती.",
    wb_region: "प.ब. क्षेत्र",
  },
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    try {
      const lang = get().language
      return translations[lang]?.[key] || translations['en']?.[key] || key
    } catch (e) {
      console.error("Translation error", e)
      return key
    }
  }
}))
